name: tandoori_bites
description: A restaurant ordering app for Tandoori Bites
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  flutter_animate: ^4.3.0
  intl: ^0.18.1
  flutter_cache_manager: ^3.3.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true